env:
  shared-node-browser: true
  commonjs: true
  es2020: true
ignorePatterns: [bin/**]
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 11
  sourceType: module
plugins: ["@typescript-eslint"]
rules:
  comma-dangle: [error, {arrays: always-multiline, objects: always-multiline, functions: never}]
  eol-last: error
  object-curly-spacing: error
  no-debugger: error
  no-multiple-empty-lines: [error, {max: 2, maxEOF: 0}]
  no-trailing-spaces: [error, ignoreComments: true]
  no-undef: error
  no-unreachable: error
  '@typescript-eslint/no-unused-vars': error
  keyword-spacing: error
  space-before-function-paren: error
root: true
